'use strict';

function titleCase(text) {
  return String(text)
    .split(/[\s._-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function renderKeyValueList(entries) {
  return entries
    .map(([key, value]) => `${key}: ${typeof value === 'string' ? value : JSON.stringify(value)}`)
    .join('\n');
}

function renderMarkdownHelp(payload) {
  const lines = [];
  lines.push(`# ${payload.title || 'Workflow CLI'}`);
  if (payload.summary) {
    lines.push('');
    lines.push(payload.summary);
  }
  lines.push('');
  lines.push('## Commands');
  for (const command of payload.commands) {
    lines.push(`- \`${command.name}\`${command.description ? `: ${command.description}` : ''}`);
  }
  return lines.join('\n');
}

function renderMarkdownStatus(payload) {
  const lines = [];
  lines.push('# Workflow Status');
  lines.push('');
  lines.push(`- Session status: ${payload.session.session.status}`);
  lines.push(`- Current state: ${payload.session.session.current_state}`);
  lines.push(`- Manifest: ${payload.manifest.name || 'unknown'}`);
  lines.push(`- Next: ${payload.suggestion.command}`);
  lines.push(`- Reason: ${payload.suggestion.reason}`);
  lines.push(
    `- Active lane: ${payload.session.session.active_lane || 'unassigned'}`,
  );
  lines.push(
    `- Active scope: ${(payload.session.session.writable_scope || []).join(', ') || 'n/a'}`,
  );
  lines.push(
    `- Hypothesis: ${payload.session.session.hypothesis || 'n/a'}`,
  );
  if (renderNextCandidateLine(payload.session.next_step)) {
    lines.push(
      `- Next candidate: ${renderNextCandidateLine(payload.session.next_step)}`,
    );
  }
  return lines.join('\n');
}

function renderMarkdownBootstrap(payload) {
  const lines = [];
  lines.push('# Bootstrap');
  lines.push('');
  lines.push(`- Manifest: ${payload.manifest.name || 'unknown'}`);
  lines.push(`- Session file: ${payload.sessionFile}`);
  lines.push(`- Session status: ${payload.session.session.status}`);
  lines.push(`- Current state: ${payload.session.session.current_state}`);
  lines.push(`- Active lane: ${payload.session.session.active_lane || 'n/a'}`);
  lines.push(
    `- Next action: ${payload.bootstrap.nextAction || 'inspect status and choose one small slice'}`,
  );
  return lines.join('\n');
}

function renderMarkdownSlice(payload) {
  const lines = [];
  lines.push(`# ${titleCase(payload.command)}`);
  lines.push('');
  if (payload.scope.length > 0) {
    lines.push('## Scope');
    for (const item of payload.scope) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }
  if (payload.hypothesis) {
    lines.push('## Hypothesis');
    lines.push(payload.hypothesis);
    lines.push('');
  }
  if (payload.reason) {
    lines.push(`Reason: ${payload.reason}`);
  }
  return lines.join('\n').trim();
}

function renderMarkdownCloseout(payload) {
  const lines = [];
  lines.push('# Closeout');
  lines.push('');
  lines.push(`- Status: ${payload.session.session.status}`);
  lines.push(`- Current state: ${payload.session.session.current_state}`);
  lines.push(`- Updated at: ${payload.session.session.updated_at || 'n/a'}`);
  lines.push(`- Slice ID: ${payload.session.session.slice_id || 'n/a'}`);
  lines.push(
    `- Scope: ${(payload.session.session.writable_scope || []).join(', ') || 'n/a'}`,
  );
  lines.push(`- Hypothesis: ${payload.session.session.hypothesis || 'n/a'}`);
  lines.push(
    `- Hypothesis outcome: ${payload.session.session.hypothesis_outcome || 'n/a'}`,
  );
  if (payload.summary) {
    lines.push('');
    lines.push('## Summary');
    lines.push(payload.summary);
  }
  return lines.join('\n');
}

function renderMarkdownChecklist(payload) {
  const lines = [];
  lines.push('# Precommit Checklist');
  lines.push('');
  for (const item of payload.items) {
    lines.push(`- [${item.done ? 'x' : ' '}] ${item.text}`);
  }
  if (payload.notes && payload.notes.length > 0) {
    lines.push('');
    lines.push('## Notes');
    for (const note of payload.notes) {
      lines.push(`- ${note}`);
    }
  }
  return lines.join('\n');
}

function renderPlain(payload) {
  if (payload.markdown) {
    return payload.markdown;
  }
  return renderKeyValueList(Object.entries(payload));
}

function renderNextCandidateLine(nextCandidate) {
  if (!nextCandidate || typeof nextCandidate !== 'object') {
    return null;
  }
  return `${nextCandidate.candidate} (${nextCandidate.status})`;
}

function renderCurrentSliceDoc(payload) {
  const lines = [];
  lines.push('# Current Slice');
  lines.push('');
  lines.push(
    'This file is generated by `scripts/workflow refresh`. Do not edit it by hand.',
  );
  lines.push('');
  lines.push(`- refreshed at: \`${payload.refreshedAt}\``);
  lines.push(`- workflow: \`${payload.manifest.name}\``);
  lines.push(`- active lane: \`${payload.session.session.active_lane || 'unassigned'}\``);
  lines.push(`- slice id: \`${payload.session.session.slice_id || 'not recorded'}\``);
  lines.push(
    `- current state: \`${payload.session.session.current_state || 'unknown'}\``,
  );
  lines.push('');
  lines.push('## Current Slice');
  lines.push('');
  lines.push(
    `- hypothesis: ${payload.session.session.hypothesis || 'not yet recorded'}`,
  );
  lines.push(
    `- hypothesis check: ${payload.session.session.hypothesis_check || 'not yet recorded'}`,
  );
  lines.push(
    `- hypothesis outcome: ${payload.session.session.hypothesis_outcome || 'not yet recorded'}`,
  );
  lines.push(
    `- writable scope: ${(payload.session.session.writable_scope || []).join(', ') || 'not yet recorded'}`,
  );
  lines.push(
    `- validation result: ${payload.session.session.validation_result || 'not yet recorded'}`,
  );
  lines.push('');
  lines.push('## Next Step');
  lines.push('');
  lines.push(`- suggested command: \`${payload.suggestion.command}\``);
  lines.push(`- reason: ${payload.suggestion.reason}`);
  if (renderNextCandidateLine(payload.session.next_step)) {
    lines.push(
      `- recorded next candidate: ${renderNextCandidateLine(payload.session.next_step)}`,
    );
  }
  return lines.join('\n');
}

function renderNextSessionPromptDoc(payload) {
  const lines = [];
  lines.push('# Next Session Prompt');
  lines.push('');
  lines.push('Read the workflow state in this order:');
  lines.push('');
  for (const item of payload.readingOrder) {
    lines.push(`- \`${item}\``);
  }
  lines.push('');
  lines.push('Then run:');
  lines.push('');
  lines.push('```text');
  lines.push('scripts/workflow bootstrap --json');
  lines.push('```');
  lines.push('');
  lines.push(`Current state: \`${payload.session.session.current_state}\``);
  lines.push(`Active lane: \`${payload.session.session.active_lane || 'unassigned'}\``);
  lines.push(`Active slice ID: \`${payload.session.session.slice_id || 'not yet recorded'}\``);
  lines.push(
    `Active hypothesis: ${payload.session.session.hypothesis || 'not yet recorded'}`,
  );
  lines.push(
    `Hypothesis check: ${payload.session.session.hypothesis_check || 'not yet recorded'}`,
  );
  lines.push(
    `Hypothesis outcome: ${payload.session.session.hypothesis_outcome || 'not yet recorded'}`,
  );
  lines.push(
    `Suggested next command: \`${payload.suggestion.command}\``,
  );
  lines.push(`Reason: ${payload.suggestion.reason}`);
  if (renderNextCandidateLine(payload.session.next_step)) {
    lines.push(
      `Recorded next candidate: ${renderNextCandidateLine(payload.session.next_step)}`,
    );
  }
  return lines.join('\n');
}

function renderGitPreflightDoc(payload) {
  const lines = [];
  lines.push('# Git Preflight');
  lines.push('');
  lines.push(`- refreshed at: \`${payload.refreshedAt}\``);
  lines.push('');
  lines.push('## Working Tree');
  lines.push('');
  lines.push('```text');
  lines.push(payload.gitSummary || '(git unavailable)');
  lines.push('```');
  lines.push('');
  lines.push('## Continue Safely');
  lines.push('');
  lines.push('- keep one writable scope at a time');
  lines.push('- stage the active slice first; let workflow state and generated docs ride along as sidecars');
  lines.push('- keep the structured workflow state authoritative');
  lines.push('- use `scripts/workflow precommit --strict --json` before commit when you want hard enforcement');
  lines.push('- refresh generated docs after changing workflow state');
  lines.push('- if refresh or formatters rewrite generated docs, restage `workflow/state/generated/*` before retrying commit');
  lines.push(
    `- current scope: ${(payload.session.session.writable_scope || []).join(', ') || 'not yet recorded'}`,
  );
  lines.push(
    `- current hypothesis: ${payload.session.session.hypothesis || 'not yet recorded'}`,
  );
  return lines.join('\n');
}

module.exports = {
  renderCurrentSliceDoc,
  renderMarkdownBootstrap,
  renderMarkdownChecklist,
  renderMarkdownCloseout,
  renderMarkdownHelp,
  renderMarkdownSlice,
  renderMarkdownStatus,
  renderGitPreflightDoc,
  renderNextSessionPromptDoc,
  renderPlain,
};
